import { del, get, list } from "@vercel/blob";

type ShareCleanupPayload = {
  kind?: string;
  value?: string;
  expiresAt?: string;
};

const SHARE_METADATA_PREFIX = "shares/";
const SHARE_METADATA_SUFFIX = ".json";
const SHARE_ID_PATTERN = /^[a-f0-9]{32}$/;
const FILE_KINDS = new Set(["image", "batch", "video", "file"]);
const SHARE_ASSET_PREFIXES = ["share-assets/", "video-uploads/"];
const OWNED_ASSET_PREFIX = "share-assets/";
const VIDEO_UPLOAD_PREFIX = "video-uploads/";

const SWEEP_BATCH_SIZE = 10;
const SWEEP_INTERVAL_MS = 10 * 60 * 1000;
// Video shares live at most 7 days, and the client uploads the video right
// before creating the share, so a video blob older than this can no longer be
// referenced by a share that is still valid.
const STALE_UPLOAD_MAX_AGE_MS = 14 * 24 * 60 * 60 * 1000;
const STALE_UPLOAD_BATCH_SIZE = 10;

let shareSweepCursor: string | undefined;
let uploadSweepCursor: string | undefined;
let lastSweepAt = 0;
let sweepInProgress = false;

function metadataPathname(shareId: string): string {
  return `${SHARE_METADATA_PREFIX}${shareId}${SHARE_METADATA_SUFFIX}`;
}

function shareIdFromMetadataPathname(pathname: string): string | null {
  if (
    !pathname.startsWith(SHARE_METADATA_PREFIX) ||
    !pathname.endsWith(SHARE_METADATA_SUFFIX)
  ) {
    return null;
  }

  const shareId = pathname.slice(
    SHARE_METADATA_PREFIX.length,
    pathname.length - SHARE_METADATA_SUFFIX.length
  );

  return SHARE_ID_PATTERN.test(shareId) ? shareId : null;
}

function shareAssetPathname(payload: ShareCleanupPayload | null | undefined): string | null {
  if (!payload || typeof payload.value !== "string") {
    return null;
  }

  if (!payload.kind || !FILE_KINDS.has(payload.kind)) {
    return null;
  }

  const value = payload.value;

  return SHARE_ASSET_PREFIXES.some((prefix) => value.startsWith(prefix))
    ? value
    : null;
}

async function deleteBlobs(pathnames: string[]): Promise<boolean> {
  if (pathnames.length === 0) {
    return true;
  }

  try {
    await del(pathnames);
    return true;
  } catch (error) {
    console.error(`Failed to delete blob(s) ${pathnames.join(", ")}:`, error);
    return false;
  }
}

async function readSharePayload(pathname: string): Promise<ShareCleanupPayload | null> {
  const blob = await get(pathname, {
    access: "private",
    useCache: false,
  });

  if (!blob || !blob.stream) {
    return null;
  }

  const text = await new Response(blob.stream).text();
  const payload = JSON.parse(text) as ShareCleanupPayload;

  return payload && typeof payload === "object" ? payload : null;
}

/**
 * Best-effort erasure of a share: the asset is removed first so a partial
 * failure never leaves an asset without its metadata (the metadata stays
 * behind and the erase is retried on the next access or sweep).
 */
export async function eraseShare(
  shareId: string,
  payload: ShareCleanupPayload | null | undefined
): Promise<void> {
  if (!SHARE_ID_PATTERN.test(shareId)) {
    return;
  }

  const asset = shareAssetPathname(payload);

  if (asset) {
    const assetDeleted = await deleteBlobs([asset]);

    if (!assetDeleted) {
      return;
    }
  }

  await deleteBlobs([metadataPathname(shareId)]);
}

/**
 * Removes the asset uploaded during a share request when saving the share
 * metadata failed, so the failed request does not orphan a blob. Only assets
 * generated by this request (`share-assets/...`) are touched.
 */
export async function cleanupUnsavedShareAsset(
  payload: ShareCleanupPayload | null | undefined
): Promise<void> {
  const asset = shareAssetPathname(payload);

  if (!asset || !asset.startsWith(OWNED_ASSET_PREFIX)) {
    return;
  }

  await deleteBlobs([asset]);
}

async function purgeIfExpired(metadata: string): Promise<boolean> {
  const shareId = shareIdFromMetadataPathname(metadata);

  if (!shareId) {
    return false;
  }

  try {
    const payload = await readSharePayload(metadata);

    if (!payload || typeof payload.expiresAt !== "string") {
      return false;
    }

    const expiresAtMs = new Date(payload.expiresAt).getTime();

    // Same rule the share endpoints use, so the sweep never deletes a share
    // that those endpoints would still serve.
    if (!Number.isFinite(expiresAtMs) || Date.now() < expiresAtMs) {
      return false;
    }

    await eraseShare(shareId, payload);
    return true;
  } catch (error) {
    console.error("Expired share sweep error:", error);
    return false;
  }
}

async function purgeExpiredShares(): Promise<number> {
  let deleted = 0;
  let examined = 0;

  while (examined < SWEEP_BATCH_SIZE) {
    const page = await list({
      prefix: SHARE_METADATA_PREFIX,
      limit: SWEEP_BATCH_SIZE - examined,
      cursor: shareSweepCursor,
    });

    if (page.blobs.length === 0) {
      shareSweepCursor = undefined;
      break;
    }

    for (const blob of page.blobs) {
      examined += 1;

      if (await purgeIfExpired(blob.pathname)) {
        deleted += 1;
      }

      if (examined >= SWEEP_BATCH_SIZE) {
        break;
      }
    }

    if (!page.hasMore || !page.cursor) {
      shareSweepCursor = undefined;
      break;
    }

    shareSweepCursor = page.cursor;
  }

  return deleted;
}

async function purgeStaleVideoUploads(): Promise<number> {
  let deleted = 0;
  let examined = 0;
  const cutoff = Date.now() - STALE_UPLOAD_MAX_AGE_MS;

  while (examined < STALE_UPLOAD_BATCH_SIZE) {
    const page = await list({
      prefix: VIDEO_UPLOAD_PREFIX,
      limit: STALE_UPLOAD_BATCH_SIZE - examined,
      cursor: uploadSweepCursor,
    });

    if (page.blobs.length === 0) {
      uploadSweepCursor = undefined;
      break;
    }

    const stale: string[] = [];

    for (const blob of page.blobs) {
      examined += 1;

      if (blob.uploadedAt.getTime() <= cutoff) {
        stale.push(blob.pathname);
      }
    }

    if (stale.length > 0 && (await deleteBlobs(stale))) {
      deleted += stale.length;
    }

    if (!page.hasMore || !page.cursor) {
      uploadSweepCursor = undefined;
      break;
    }

    uploadSweepCursor = page.cursor;
  }

  return deleted;
}

/**
 * Throttled, bounded cleanup sweep meant to run after a response (via
 * `after`). It only ever deletes expired shares and stale uploads, so it is
 * safe to trigger opportunistically from existing share traffic.
 */
export async function maybeRunShareCleanup(): Promise<void> {
  const now = Date.now();

  if (sweepInProgress || now - lastSweepAt < SWEEP_INTERVAL_MS) {
    return;
  }

  sweepInProgress = true;
  lastSweepAt = now;

  try {
    const expiredShares = await purgeExpiredShares();
    const staleUploads = await purgeStaleVideoUploads();

    if (expiredShares > 0 || staleUploads > 0) {
      console.log(
        `Share cleanup: erased ${expiredShares} expired share(s) and ${staleUploads} stale upload(s).`
      );
    }
  } catch (error) {
    shareSweepCursor = undefined;
    uploadSweepCursor = undefined;
    console.error("Share cleanup error:", error);
  } finally {
    sweepInProgress = false;
  }
}
